[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[nLogger]
USE = true

[ValidatingComponents]
USE = true

[Components]
Count = 4

;그 외 관리자 실행
;*RTICommunicationManager가 후반부에 실행
;CommandManager는 가장 마지막에 실행

[Component_1]
PATH = LaunchManager
DLL = LaunchManager
XML = LaunchManager.xml
POWER = on

[Component_2]
PATH = LCSModelManager
DLL = LCSModelManager
XML = LCSModelManager.xml
POWER = on

[Component_3]
PATH = SimulationManager
DLL = SimulationManager
XML = SimulationManager.xml
POWER = on

[Component_4]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on
