[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[nLogger]
USE = true

[ValidatingComponents]
USE = true

[ComponentsOnNFConnect]
Count = 2

[ComponentOnNFConnect_1]
PATH = UIManager
MANAGER = UIManager
XML = UIManager.xml

[ComponentOnNFConnect_2]
PATH = NewRoleManager
MANAGER = NewRoleManager
XML = NewRoleManager.xml

[Components]
Count = 11

;UIManager는 가장 먼저 실행
;그 외 관리자 실행
;*RTICommunicationManager가 후반부에 실행

[Component_1]
PATH = UIManager
DLL = UIManager
XML = UIManager.xml
POWER = on

[Component_2]
PATH = NewRoleManager
DLL = NewRoleManager
XML = NewRoleManager.xml
POWER = on

[Component_3]
PATH = FooManager
DLL = FooManager
XML = FooManager.xml
POWER = off

[Component_4]
PATH = BarManager
DLL = BarManager
XML = BarManager.xml
POWER = off

[Component_5]
PATH = RTICommunicationManager
DLL = RTICommunicationManager
XML = RTICommunicationManager.xml
POWER = off

[Component_6]
PATH = DDSCommunicationManager
DLL = DDSCommunicationManager
XML = DDSCommunicationManager.xml
POWER = off

[Component_7]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on

[Component_8]
PATH = TCPCommunicationManager
DLL = TCPCommunicationManager
XML = TCPCommunicationManager.xml
POWER = off

[Component_9]
PATH = ATSManager
DLL = ATSManager
XML = ATSManager.xml
POWER = on

[Component_10]
PATH = StateManager
DLL = StateManager
XML = StateManager.xml
POWER = on

[Component_11]
PATH = SimulationManager
DLL = SimulationManager
XML = SimulationManager.xml
POWER = on

