[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[nLogger]
USE = true

[ValidatingComponents]
USE = true

[Components]
Count = 4

;그 외 관리자 실행
;*RTICommunicationManager가 후반부에 실행
;CommandManager는 가장 마지막에 실행

[Component_1]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on

[Component_2]
PATH = UIManager
DLL = UIManager
XML = UIManager.xml
POWER = on

[Component_3]
PATH = CommandManager
DLL = CommandManager
XML = CommandManager.xml
POWER = on

[Component_4]
PATH = StateManager
DLL = StateManager
XML = StateManager.xml
POWER = on
