[LOCAL]
IP =192.168.0.4
PORT =10000

[REMOTE]
IP =192.168.0.14
PORT =10000

[MULTICAST]
IP =224.0.0.100
PORT =10000

[BROADCAST]
IP =255.255.255.255
PORT =10000

[SERVICE]
PROTOCOL =UDP
;TCP, UDP
ROLE = SEND
;SEND, RECEIVE
CAST = UNICAST
;NS UNICAST, MULTICAST , BROADCAST

[HEADER]
SIZE = 4
ID_POS = 0
ID_SIZE = 2
LEN_POS = 2
LEN_SIZE = 2


ID_SIZE = 2
LEN_POS = 2
LEN_SIZE = 2
