[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[nLogger]
USE = true

[ValidatingComponents]
USE = true

[Components]
Count = 3

;그 외 관리자 실행
;*RTICommunicationManager가 후반부에 실행
;CommandManager는 가장 마지막에 실행

[Component_1]
PATH = MSSCommandManager
DLL = MSSCommandManager
XML = MSSCommandManager.xml
POWER = on


[Component_2]
PATH = MSSModelManager
DLL = MSSModelManager
XML = MSSModelManager.xml
POWER = on

[Component_3]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on