; CommLinkInfo.ini — MSS receiver (multicast)

[LOCAL]
IP = 127.0.0.1
PORT = 10004

[REMOTE]
IP = 239.255.0.1
PORT = 10000

[SERVICE]
PROTOCOL = UDP
ROLE = SEND
CAST = MULTICAST

[MULTICAST]
IP = 239.255.0.1
PORT = 10000

[HEADER]
SIZE = 8
ID_POS = 0
ID_SIZE = 4
LEN_POS = 4
LEN_SIZE = 4
