; CommLinkInfo.ini - MSS (ROLE=RECEIVE)
; Mode: Local unicast test
; MSS receives on 127.0.0.1:10004

[LOCAL]
IP = 127.0.0.1
PORT = 10004

[REMOTE]
IP = 127.0.0.1
PORT = 10000

[MULTICAST]
IP = 224.0.0.100
PORT = 10000

[BROADCAST]
IP = 255.255.255.255
PORT = 10000

[SERVICE]
PROTOCOL =UDP
ROLE = RECEIVE
CAST = UNICAST

[HEADER]
SIZE = 8
ID_POS = 0
ID_SIZE = 4
LEN_POS = 4
LEN_SIZE = 4
