[LOCAL]
IP =169.254.193.187
PORT =10000

[REMOTE]
IP =172.16.12.45
PORT =10000

[MULTICAST]
IP =224.0.0.100
PORT =10000

[BROADCAST]
IP =255.255.255.255
PORT =10000

[SERVICE]
PROTOCOL =UDP
;TCP, UDP
ROLE = RECEIVE
;SEND, RECEIVE
CAST =MULTICAST
;NS UNICAST, MULTICAST , BROADCAST

[HEADER]
SIZE = 8
ID_POS = 0
ID_SIZE = 4
LEN_POS = 4
LEN_SIZE = 4